// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"casicloud.com/ylops/backend/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	routerRouter := &router.Router{}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
