groups:
- name: alert.rules
  rules:
  - alert: SiteUnreachable
    expr: probe_success == 0
    for: 10s
    labels:
      severity: "critical"
    annotations:
      summary: "Site {{ $labels.instance }} unreachable"