global:
  resolve_timeout: 5m
  http_config:
    tls_config:
      insecure_skip_verify: true
templates:
  - '/templates/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'htyx'
  routes:
  - receiver: 'web.hook'
    continue: true
  - receiver: 'htyx'
receivers:
- name: 'htyx'
  htyx_configs:
  - send_resolved: true
    api_url: 'https://htyx.casicloud.com/cgi-bin/'
    api_secret: '-j8sK32tdcyWuEcwdXtIz7B8k1CmJXE_A5NuwLhRPOA'
    corp_id: 'wlb07f8823a2'
    agent_id: '1000091'
    chat_id: '14942099138737219377'
    message: '{{ template "site.default.message" . }}'
- name: 'web.hook'
  webhook_configs:
  - url: 'http://172.20.4.86:5001/'
